SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Stock](
	[ItemID] [int] NOT NULL,
	[ItemName] [varchar](20) NOT NULL,
	[ItemPrice] [decimal](4, 2) NULL,
	[ItemStock] [int] NULL,
	[ItemType] [varchar](20) NULL,
 CONSTRAINT [Stock_pk] PRIMARY KEY CLUSTERED 
(
	[ItemID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
